### ISSUE TITLE
Pyyaml version not supported 

### ISSUE THREAD

**Issue by JudyJin** [Rose-STL-Lab/Spatiotemporal_UQ#3]
Issue with
File "dcrnn_train_pytorch.py", line 15, in main
    supervisor_config = yaml.load(f)
TypeError: load() missing 1 required positional argument: 'Loader'

I think this work either specify pyyaml version == 5.4.1, or add the Loader argument

**Comment by DongxiaW** [comment]
Thanks. I've updated pyyaml version.
