### ISSUE TITLE
Memory Error while running SG-MCMC on a large dataset with 2700 nodes

### ISSUE THREAD

**Issue by tanwimallick** [Rose-STL-Lab/Spatiotemporal_UQ#4]
Here is the error I got while running the SG-MCMC model on A100 GRU on relatively large dataset with 2700 nodes

x = torch.reshape(x, shape=[batch_size * self._num_nodes, input_size * num_matrices])
RuntimeError: CUDA out of memory. Tried to allocate 426.00 MiB (GPU 0; 39.59 GiB total capacity; 35.84 GiB already allocated; 396.19 MiB free; 37.63 GiB reserved in total by PyTorch)

**Comment by DongxiaW** [comment]
You can try to reduce the batch size to save the memory. We run the code on GeForce RTX 2080 GPU.
